# Generated by Django 2.2 on 2019-04-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.FileField(upload_to='photos/%Y/%m/%d/')),
                ('course', models.CharField(choices=[('BCSIT', 'BCSIT'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=100)),
                ('admission_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
