# Generated by Django 2.2 on 2019-05-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190505_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='photos/%Y/%M/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='krbaidik0@gmail.com', max_length=30),
        ),
    ]
